// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Station struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image                string   `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Station) Reset()         { *m = Station{} }
func (m *Station) String() string { return proto.CompactTextString(m) }
func (*Station) ProtoMessage()    {}
func (*Station) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *Station) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Station.Unmarshal(m, b)
}
func (m *Station) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Station.Marshal(b, m, deterministic)
}
func (m *Station) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Station.Merge(m, src)
}
func (m *Station) XXX_Size() int {
	return xxx_messageInfo_Station.Size(m)
}
func (m *Station) XXX_DiscardUnknown() {
	xxx_messageInfo_Station.DiscardUnknown(m)
}

var xxx_messageInfo_Station proto.InternalMessageInfo

func (m *Station) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Station) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Station) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

type Response struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type StartRequest struct {
	Station              *Station `protobuf:"bytes,2,opt,name=station,proto3" json:"station,omitempty"`
	UserID               string   `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartRequest) Reset()         { *m = StartRequest{} }
func (m *StartRequest) String() string { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()    {}
func (*StartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

func (m *StartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartRequest.Unmarshal(m, b)
}
func (m *StartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartRequest.Marshal(b, m, deterministic)
}
func (m *StartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartRequest.Merge(m, src)
}
func (m *StartRequest) XXX_Size() int {
	return xxx_messageInfo_StartRequest.Size(m)
}
func (m *StartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartRequest proto.InternalMessageInfo

func (m *StartRequest) GetStation() *Station {
	if m != nil {
		return m.Station
	}
	return nil
}

func (m *StartRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *StartRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Station)(nil), "loko.metro.api.Station")
	proto.RegisterType((*Response)(nil), "loko.metro.api.Response")
	proto.RegisterType((*StartRequest)(nil), "loko.metro.api.StartRequest")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x31, 0x4f, 0xc3, 0x40,
	0x0c, 0x85, 0xd5, 0xd0, 0x36, 0x60, 0xaa, 0x0e, 0x27, 0x04, 0x99, 0x50, 0x95, 0x89, 0xe9, 0x22,
	0x60, 0x61, 0x06, 0x16, 0xd6, 0xeb, 0xc6, 0x76, 0x4d, 0xac, 0x72, 0x02, 0xc7, 0x21, 0x76, 0xfe,
	0x3f, 0x8a, 0x93, 0x4a, 0x74, 0xf3, 0xb3, 0xfc, 0xde, 0xfb, 0x64, 0xd8, 0xd4, 0x4c, 0xc4, 0xad,
	0xef, 0x7a, 0x56, 0x76, 0xdb, 0x1f, 0xfe, 0x66, 0x4f, 0xa8, 0x3d, 0xfb, 0xd8, 0xa5, 0xf2, 0x0d,
	0xf2, 0xbd, 0x46, 0x4d, 0xdc, 0xba, 0x2d, 0x64, 0xa9, 0x29, 0x16, 0xbb, 0xc5, 0xc3, 0x55, 0xc8,
	0x52, 0xe3, 0x1c, 0x2c, 0xdb, 0x48, 0x58, 0x64, 0xb6, 0xb1, 0xd9, 0xdd, 0xc0, 0x2a, 0x51, 0x3c,
	0x62, 0x71, 0x61, 0xcb, 0x49, 0x94, 0x2f, 0x70, 0x19, 0x50, 0x3a, 0x6e, 0x05, 0x47, 0x57, 0xcd,
	0x0d, 0x5a, 0xce, 0x2a, 0xd8, 0xec, 0x0a, 0xc8, 0x09, 0x45, 0x46, 0xdf, 0x14, 0x76, 0x92, 0xa5,
	0xc0, 0x66, 0xaf, 0xb1, 0xd7, 0x80, 0xbf, 0x03, 0x8a, 0xba, 0x47, 0xc8, 0x65, 0xc2, 0xb1, 0xcb,
	0xeb, 0xa7, 0x3b, 0x7f, 0x0e, 0xec, 0x67, 0xda, 0x70, 0xba, 0x73, 0xb7, 0xb0, 0x1e, 0x04, 0xfb,
	0x8f, 0xf7, 0x99, 0x69, 0x56, 0xff, 0x4b, 0x97, 0x67, 0xa5, 0xaf, 0xbb, 0xcf, 0xfb, 0x63, 0xd2,
	0xaf, 0xe1, 0xe0, 0x6b, 0xa6, 0x6a, 0xcc, 0x27, 0x56, 0x94, 0xca, 0x4a, 0xaa, 0xd8, 0xa5, 0xc3,
	0xda, 0x9e, 0xf5, 0xfc, 0x17, 0x00, 0x00, 0xff, 0xff, 0xad, 0xef, 0x4a, 0x1e, 0x3c, 0x01, 0x00,
	0x00,
}
