// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ctl.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoadRequest struct {
	// required(image)
	Station              *Station `protobuf:"bytes,2,opt,name=station,proto3" json:"station,omitempty"`
	UserID               string   `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadRequest) Reset()         { *m = LoadRequest{} }
func (m *LoadRequest) String() string { return proto.CompactTextString(m) }
func (*LoadRequest) ProtoMessage()    {}
func (*LoadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0646114e50303026, []int{0}
}

func (m *LoadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadRequest.Unmarshal(m, b)
}
func (m *LoadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadRequest.Marshal(b, m, deterministic)
}
func (m *LoadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadRequest.Merge(m, src)
}
func (m *LoadRequest) XXX_Size() int {
	return xxx_messageInfo_LoadRequest.Size(m)
}
func (m *LoadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadRequest proto.InternalMessageInfo

func (m *LoadRequest) GetStation() *Station {
	if m != nil {
		return m.Station
	}
	return nil
}

func (m *LoadRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func init() {
	proto.RegisterType((*LoadRequest)(nil), "loko.metro.api.LoadRequest")
}

func init() { proto.RegisterFile("ctl.proto", fileDescriptor_0646114e50303026) }

var fileDescriptor_0646114e50303026 = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2e, 0xc9, 0xd1,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xcb, 0xc9, 0xcf, 0xce, 0xd7, 0xcb, 0x4d, 0x2d, 0x29,
	0xca, 0xd7, 0x4b, 0x2c, 0xc8, 0x94, 0xe2, 0x49, 0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0x83, 0xc8, 0x2a,
	0x45, 0x70, 0x71, 0xfb, 0xe4, 0x27, 0xa6, 0x04, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x19,
	0x72, 0xb1, 0x17, 0x97, 0x24, 0x96, 0x64, 0xe6, 0xe7, 0x49, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x1b,
	0x89, 0xeb, 0xa1, 0x6a, 0xd7, 0x0b, 0x86, 0x48, 0x07, 0xc1, 0xd4, 0x09, 0x89, 0x71, 0xb1, 0x95,
	0x16, 0xa7, 0x16, 0x79, 0xba, 0x48, 0x30, 0x2b, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x79, 0x46, 0x9d,
	0x8c, 0x5c, 0xcc, 0xce, 0x25, 0x39, 0x42, 0x8e, 0x5c, 0xac, 0xc1, 0x25, 0x89, 0x45, 0x25, 0x42,
	0x32, 0x58, 0x8c, 0x2a, 0x2a, 0x81, 0xda, 0x2c, 0x25, 0x81, 0x2e, 0x1b, 0x94, 0x5a, 0x5c, 0x90,
	0x9f, 0x57, 0x9c, 0xaa, 0xc4, 0x20, 0x64, 0xcf, 0xc5, 0x02, 0x72, 0xa4, 0x90, 0x34, 0xba, 0x1a,
	0x24, 0xa7, 0xe3, 0x33, 0xc0, 0x49, 0x21, 0x4a, 0x2e, 0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f,
	0x39, 0x3f, 0x57, 0x1f, 0xa4, 0x2e, 0x37, 0xbf, 0x24, 0xb5, 0x58, 0x1f, 0xac, 0x58, 0x3f, 0xb1,
	0x20, 0x33, 0x89, 0x0d, 0x1c, 0x1c, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6f, 0x86, 0x0e,
	0x56, 0x39, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CtlClient is the client API for Ctl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CtlClient interface {
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*Response, error)
	Load(ctx context.Context, in *LoadRequest, opts ...grpc.CallOption) (*Response, error)
}

type ctlClient struct {
	cc *grpc.ClientConn
}

func NewCtlClient(cc *grpc.ClientConn) CtlClient {
	return &ctlClient{cc}
}

func (c *ctlClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/loko.metro.api.Ctl/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ctlClient) Load(ctx context.Context, in *LoadRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/loko.metro.api.Ctl/Load", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CtlServer is the server API for Ctl service.
type CtlServer interface {
	Start(context.Context, *StartRequest) (*Response, error)
	Load(context.Context, *LoadRequest) (*Response, error)
}

// UnimplementedCtlServer can be embedded to have forward compatible implementations.
type UnimplementedCtlServer struct {
}

func (*UnimplementedCtlServer) Start(ctx context.Context, req *StartRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (*UnimplementedCtlServer) Load(ctx context.Context, req *LoadRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Load not implemented")
}

func RegisterCtlServer(s *grpc.Server, srv CtlServer) {
	s.RegisterService(&_Ctl_serviceDesc, srv)
}

func _Ctl_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CtlServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/loko.metro.api.Ctl/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CtlServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ctl_Load_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CtlServer).Load(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/loko.metro.api.Ctl/Load",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CtlServer).Load(ctx, req.(*LoadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ctl_serviceDesc = grpc.ServiceDesc{
	ServiceName: "loko.metro.api.Ctl",
	HandlerType: (*CtlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _Ctl_Start_Handler,
		},
		{
			MethodName: "Load",
			Handler:    _Ctl_Load_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ctl.proto",
}
